version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "search-insights"
        dependency-type: "production"
    commit-message:
      prefix: "chore"
